### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by andrewschouten** [sswayney/seq-logback-appender#10]
https://github.com/sswayney/seq-logback-appender/blob/069804da1570b2dcf0ccb59a74632557f5531953/src/main/resources/seq-logback-settings.xml#L14

I think the class has moved to ses.seq.logback.appender.layout.base.SeqLogEventLayout

**Comment by sswayney** [comment]
You sure this isn't the real issue for Error SEQ_LAYOUT_IS_UNDEFINED #9 ? I tested #9 a few times and it was working. But maybe something changed.

**Comment by sswayney** [comment]
Fixed in release 0.1.4
