### ISSUE TITLE
Error SEQ_LAYOUT_IS_UNDEFINED

### ISSUE THREAD

**Issue by andrewschouten** [sswayney/seq-logback-appender#9]
https://github.com/sswayney/seq-logback-appender/blob/069804da1570b2dcf0ccb59a74632557f5531953/src/main/resources/seq-logback-settings.xml#L15

Looks like wrong syntax for the default, try:

${SEQ_LAYOUT:-${DEFAULT_SEQ_LAYOUT}}

**Comment by sswayney** [comment]
Fixed in release 0.1.4
